/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as meetingRouteRouteImport } from './routes/(meeting)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appVtoIndexRouteImport } from './routes/(app)/vto/index'
import { Route as appTodosIndexRouteImport } from './routes/(app)/todos/index'
import { Route as appSettingsIndexRouteImport } from './routes/(app)/settings/index'
import { Route as appScorecardsIndexRouteImport } from './routes/(app)/scorecards/index'
import { Route as appRocksIndexRouteImport } from './routes/(app)/rocks/index'
import { Route as appL10MeetingsIndexRouteImport } from './routes/(app)/l10-meetings/index'
import { Route as appIssuesIndexRouteImport } from './routes/(app)/issues/index'
import { Route as appHeadlinesIndexRouteImport } from './routes/(app)/headlines/index'
import { Route as meetingL10MeetingsMeetingIdRouteImport } from './routes/(meeting)/l10-meetings/$meetingId'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const meetingRouteRoute = meetingRouteRouteImport.update({
  id: '/(meeting)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appVtoIndexRoute = appVtoIndexRouteImport.update({
  id: '/vto/',
  path: '/vto/',
  getParentRoute: () => appRouteRoute,
} as any)
const appTodosIndexRoute = appTodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => appRouteRoute,
} as any)
const appScorecardsIndexRoute = appScorecardsIndexRouteImport.update({
  id: '/scorecards/',
  path: '/scorecards/',
  getParentRoute: () => appRouteRoute,
} as any)
const appRocksIndexRoute = appRocksIndexRouteImport.update({
  id: '/rocks/',
  path: '/rocks/',
  getParentRoute: () => appRouteRoute,
} as any)
const appL10MeetingsIndexRoute = appL10MeetingsIndexRouteImport.update({
  id: '/l10-meetings/',
  path: '/l10-meetings/',
  getParentRoute: () => appRouteRoute,
} as any)
const appIssuesIndexRoute = appIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => appRouteRoute,
} as any)
const appHeadlinesIndexRoute = appHeadlinesIndexRouteImport.update({
  id: '/headlines/',
  path: '/headlines/',
  getParentRoute: () => appRouteRoute,
} as any)
const meetingL10MeetingsMeetingIdRoute =
  meetingL10MeetingsMeetingIdRouteImport.update({
    id: '/l10-meetings/$meetingId',
    path: '/l10-meetings/$meetingId',
    getParentRoute: () => meetingRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/login': typeof authLoginRoute
  '/': typeof appIndexRoute
  '/l10-meetings/$meetingId': typeof meetingL10MeetingsMeetingIdRoute
  '/headlines/': typeof appHeadlinesIndexRoute
  '/issues/': typeof appIssuesIndexRoute
  '/l10-meetings/': typeof appL10MeetingsIndexRoute
  '/rocks/': typeof appRocksIndexRoute
  '/scorecards/': typeof appScorecardsIndexRoute
  '/settings/': typeof appSettingsIndexRoute
  '/todos/': typeof appTodosIndexRoute
  '/vto/': typeof appVtoIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/login': typeof authLoginRoute
  '/': typeof appIndexRoute
  '/l10-meetings/$meetingId': typeof meetingL10MeetingsMeetingIdRoute
  '/headlines': typeof appHeadlinesIndexRoute
  '/issues': typeof appIssuesIndexRoute
  '/l10-meetings': typeof appL10MeetingsIndexRoute
  '/rocks': typeof appRocksIndexRoute
  '/scorecards': typeof appScorecardsIndexRoute
  '/settings': typeof appSettingsIndexRoute
  '/todos': typeof appTodosIndexRoute
  '/vto': typeof appVtoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(meeting)': typeof meetingRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/(auth)/login': typeof authLoginRoute
  '/(app)/': typeof appIndexRoute
  '/(meeting)/l10-meetings/$meetingId': typeof meetingL10MeetingsMeetingIdRoute
  '/(app)/headlines/': typeof appHeadlinesIndexRoute
  '/(app)/issues/': typeof appIssuesIndexRoute
  '/(app)/l10-meetings/': typeof appL10MeetingsIndexRoute
  '/(app)/rocks/': typeof appRocksIndexRoute
  '/(app)/scorecards/': typeof appScorecardsIndexRoute
  '/(app)/settings/': typeof appSettingsIndexRoute
  '/(app)/todos/': typeof appTodosIndexRoute
  '/(app)/vto/': typeof appVtoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/login'
    | '/'
    | '/l10-meetings/$meetingId'
    | '/headlines/'
    | '/issues/'
    | '/l10-meetings/'
    | '/rocks/'
    | '/scorecards/'
    | '/settings/'
    | '/todos/'
    | '/vto/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/login'
    | '/'
    | '/l10-meetings/$meetingId'
    | '/headlines'
    | '/issues'
    | '/l10-meetings'
    | '/rocks'
    | '/scorecards'
    | '/settings'
    | '/todos'
    | '/vto'
  id:
    | '__root__'
    | '/(app)'
    | '/(meeting)'
    | '/$'
    | '/(auth)/login'
    | '/(app)/'
    | '/(meeting)/l10-meetings/$meetingId'
    | '/(app)/headlines/'
    | '/(app)/issues/'
    | '/(app)/l10-meetings/'
    | '/(app)/rocks/'
    | '/(app)/scorecards/'
    | '/(app)/settings/'
    | '/(app)/todos/'
    | '/(app)/vto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  meetingRouteRoute: typeof meetingRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(meeting)': {
      id: '/(meeting)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof meetingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/vto/': {
      id: '/(app)/vto/'
      path: '/vto'
      fullPath: '/vto/'
      preLoaderRoute: typeof appVtoIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/todos/': {
      id: '/(app)/todos/'
      path: '/todos'
      fullPath: '/todos/'
      preLoaderRoute: typeof appTodosIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/': {
      id: '/(app)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof appSettingsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/scorecards/': {
      id: '/(app)/scorecards/'
      path: '/scorecards'
      fullPath: '/scorecards/'
      preLoaderRoute: typeof appScorecardsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/rocks/': {
      id: '/(app)/rocks/'
      path: '/rocks'
      fullPath: '/rocks/'
      preLoaderRoute: typeof appRocksIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/l10-meetings/': {
      id: '/(app)/l10-meetings/'
      path: '/l10-meetings'
      fullPath: '/l10-meetings/'
      preLoaderRoute: typeof appL10MeetingsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/issues/': {
      id: '/(app)/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof appIssuesIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/headlines/': {
      id: '/(app)/headlines/'
      path: '/headlines'
      fullPath: '/headlines/'
      preLoaderRoute: typeof appHeadlinesIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(meeting)/l10-meetings/$meetingId': {
      id: '/(meeting)/l10-meetings/$meetingId'
      path: '/l10-meetings/$meetingId'
      fullPath: '/l10-meetings/$meetingId'
      preLoaderRoute: typeof meetingL10MeetingsMeetingIdRouteImport
      parentRoute: typeof meetingRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appHeadlinesIndexRoute: typeof appHeadlinesIndexRoute
  appIssuesIndexRoute: typeof appIssuesIndexRoute
  appL10MeetingsIndexRoute: typeof appL10MeetingsIndexRoute
  appRocksIndexRoute: typeof appRocksIndexRoute
  appScorecardsIndexRoute: typeof appScorecardsIndexRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
  appTodosIndexRoute: typeof appTodosIndexRoute
  appVtoIndexRoute: typeof appVtoIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appHeadlinesIndexRoute: appHeadlinesIndexRoute,
  appIssuesIndexRoute: appIssuesIndexRoute,
  appL10MeetingsIndexRoute: appL10MeetingsIndexRoute,
  appRocksIndexRoute: appRocksIndexRoute,
  appScorecardsIndexRoute: appScorecardsIndexRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
  appTodosIndexRoute: appTodosIndexRoute,
  appVtoIndexRoute: appVtoIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface meetingRouteRouteChildren {
  meetingL10MeetingsMeetingIdRoute: typeof meetingL10MeetingsMeetingIdRoute
}

const meetingRouteRouteChildren: meetingRouteRouteChildren = {
  meetingL10MeetingsMeetingIdRoute: meetingL10MeetingsMeetingIdRoute,
}

const meetingRouteRouteWithChildren = meetingRouteRoute._addFileChildren(
  meetingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  meetingRouteRoute: meetingRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
